### ISSUE TITLE
Error While running the hello world example in pycharm

### ISSUE THREAD

**Issue by nsksai6** [CLevasseur/grpc-kubernetes#1]
Traceback (most recent call last):
  File "grpc-kubernetes/client.py", line 21, in <module>
    run(args.server_ip)
  File "grpc-kubernetes/client.py", line 13, in run
    response = stub.handle_request(service_pb2.Request(name='you'))
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 487, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 437, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

Can anyone please help me with this issue I have attached my code below
Thanks in advance :)
[SimplegRPC.zip](https://github.com/CLevasseur/grpc-kubernetes/files/6565115/SimplegRPC.zip)

**Comment by nsksai6** [comment]
CLevasseur please look into it thanks.

**Comment by aqibamin7** [comment]
Even i'm facing the same error.
Carl Levasseur can you please help us to debug this error.
Thanks
